"""dell_salts_db.py — GENERATED by build_salts_db.py
Facts extracted from real Dell firmware data collected from
the internet (relay/catalog.txt -> bios-analysis/collected/),
plus the original reference modules. Do not hand-edit;
regenerate with: python3 build_salts_db.py
See REPORT.md §13 for the construction this database feeds.
"""

import hashlib

DB = [{'file': '/home/user/Zte/bios-analysis/collected/Latitude_5300_1.37.0/pw_3_23552.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5300_1.37.0/pw_4_25600.efi', 'size': 25600, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': [], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5300_1.37.0/pw_5_30208.efi', 'size': 30208, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5300_1.37.0/pw_7_42496.efi', 'size': 42496, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['31443342', '8dfc7b25'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_11_42496.efi', 'size': 42496, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_12_43008.efi', 'size': 43008, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_3_16896.efi', 'size': 16896, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_4_23552.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_5_24576.efi', 'size': 24576, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': [], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_6_25600.efi', 'size': 25600, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': [], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_7_30208.efi', 'size': 30208, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X00_Precision_3540_1.43.1/pw_8_31744.efi', 'size': 31744, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X90_1.41.0/pw_1_23552.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X90_1.41.0/pw_2_24576.efi', 'size': 24576, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': [], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X90_1.41.0/pw_3_25600.efi', 'size': 25600, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/Latitude_5X90_1.41.0/pw_5_42496.efi', 'size': 42496, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3040_1.20.1/pw_1_15872.efi', 'size': 15872, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3040_1.20.1/pw_4_42496.efi', 'size': 42496, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3070_1.35.0/pw_4_24576.efi', 'size': 24576, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': [], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3070_1.35.0/pw_5_25600.efi', 'size': 25600, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3080_2.33.0/pw_2_25600.efi', 'size': 25600, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': [], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3080_2.33.0/pw_3_30208.efi', 'size': 30208, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': False},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3080_2.33.0/pw_4_43008.efi', 'size': 43008, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3090_2.0.7/pw_3_31744.efi', 'size': 31744, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3090_UFF_1.42.0/pw_3_38912.efi', 'size': 38912, 'sha256_build': None, 'salts': ['31443342'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/collected/OptiPlex_3240_1.13.0/pw_1_16896.efi', 'size': 16896, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5300_pw1.efi', 'size': 42496, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['31443342', '8dfc7b25'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5300_pw2.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5X90_pw0.efi', 'size': 42496, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5X90_pw1.efi', 'size': 25600, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5X90_pw2.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/Latitude_5X90_pw3.efi', 'size': 24576, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': [], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.0.7_pw_23k.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.0.7_pw_24k.efi', 'size': 24576, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': [], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.0.7_pw_31k.efi', 'size': 31744, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.0.7_pw_42k.efi', 'size': 42496, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.27.0_pw_23k.efi', 'size': 23552, 'sha256_build': '1.0.2k  26 Jan 2017', 'salts': ['30303031'], 'family_lists': [['8FC8']], 'platform_types': None, 'alphabet': True},
      {'file': '/home/user/Zte/bios-analysis/optiplex3090/pwmods/optiplex3090_2.27.0_pw_43k.efi', 'size': 43008, 'sha256_build': '1.0.2zk  3 Sep 2024', 'salts': ['32413742', '42463937', '8dfc7b25'], 'family_lists': [['1B58', '9ABE', '3FE2', 'CF1B', '8FC8']], 'platform_types': None, 'alphabet': True}]


def challenge_hash(data, salt=bytes.fromhex("8dfc7b25")):
    """SHA256(data || salt) — the EC-path challenge primitive."""
    return hashlib.sha256(bytes(data) + bytes(salt)).digest()


def all_salts():
    """Every distinct salt seen across all real modules."""
    s = set()
    for e in DB:
        s.update(e.get("salts", []))
    return sorted(s)


if __name__ == "__main__":
    print(f"{len(DB)} modules in DB")
    print("distinct salts:", all_salts())
