#!/usr/bin/env python3
"""
dell_master_keygen.py — THE tag + suffix -> BIOS master password generator
for the Dell OptiPlex 3090 (target: H2FS5S3) and its firmware generation.

    usage: sudo python3 dell_master_keygen.py --tag H2FS5S3 --suffix CF1B

WHAT THIS TOOL IS
-----------------
A single keygen source covering every password family this machine's
firmware knows, each derived from THAT family's own implementation in the
machine's own vault module (no cross-family copying):

  * LOCAL families (E7A8, BF97, 6FF1, 1F66, 1D3B, 2A7B, 0001):
    the master is generated by CPU-emulating the vault module's own
    generator function (fn_b) — the same bytes the SMM would produce.
    Fully offline. (Note: E7A8 params are per-BIOS-branch rotated; this
    tool always uses YOUR module's params because it runs YOUR module.)

  * EC families (CF1B, 8FC8, 9ABE, 3FE2, 1B58):
    the master is computed by the embedded controller from
    (service tag, family byte) — proven by full protocol reversal and
    Unicorn emulation of the SMM session function (CF1B_FINDINGS.md §11):

        open  {0x21, 0x00, 0x03, 0x06}     (cmd 0x21, sub 3, type 6)
        send  <service tag bytes>
        send  <family LSB>                 (CF1B=0x1B, 8FC8=0xC8, ...)
        recv  32 bytes                     <- the master material
        recv  1 status byte                (0x00 = success)

    then the response->code map (fn 0x8E18, all branches emulation-verified):
        CF1B/3FE2/1B58/9ABE -> master = resp[0:16] VERBATIM
        8FC8                -> master[i] = alphabet[(resp[i]+resp[i+16]) % 72]

    The EC-side transform (tag,family)->resp32 is sealed in EC silicon with
    a fused AES key — proven absent from every public firmware image
    (CF1B_FINDINGS.md §11.7). It is therefore invoked as an ORACLE:

      --oracle local      run on the target machine: direct EC mailbox I/O
                          via /dev/port (bare metal, root). This is the only
                          possible standalone keygen for EC families.
      --oracle resp:HEX   offline: supply a captured 64-hex-char EC response
                          (from this tool's --oracle local run, a Dell
                          readout, or any future leak); the tool applies the
                          verified map and prints the master.

SELF-TEST:  python3 dell_master_keygen.py --selftest
Validates the response->code maps against the emulation vectors and the
module-emulation path against the 3090's own E7A8 output.
"""
import argparse
import os
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_PE = os.path.join(HERE, "firmware", "vault_3090_2.27.0_cf1b.pe")

# ---------------------------------------------------------------------------
# family data — all values read from / verified against the machine's own
# 2.27.0 vault module (CF1B_FINDINGS.md §11.2, §11.3)
# ---------------------------------------------------------------------------
FAMILY_LSB = {          # byte the SMM sends for each EC family (emulation-proven)
    0x1B58: 0x58, 0x9ABE: 0xBE, 0x3FE2: 0xE2, 0xCF1B: 0x1B, 0x8FC8: 0xC8,
}
EC_FAMILIES = set(FAMILY_LSB)
LOCAL_FAMILIES = (0xE7A8, 0xBF97, 0x6FF1, 0x1F66, 0x1D3B, 0x2A7B, 0x0001)

# module layout (3090 2.27.0 inner PE)
VA_ALPHA_TABLE = 0xa9e0        # dispatch table: qword alphabet pointers
LEGACY_LIST_VA = 0xa3b8        # E7A8,BF97,6FF1,1F66,1D3B,2A7B,0001,FFFF
EC_LIST_VA     = 0xa3c8        # 1B58,9ABE,3FE2,CF1B,8FC8,FFFF

DEFAULT_TAG = "H2FS5S3"


def pe_sections(pe):
    e = struct.unpack_from("<I", pe, 0x3c)[0]
    n = struct.unpack_from("<H", pe, e + 6)[0]
    optsz = struct.unpack_from("<H", pe, e + 20)[0]
    out, off = [], e + 24 + optsz
    for _ in range(n):
        nm = pe[off:off + 8].rstrip(b"\0").decode("latin1", "replace")
        vs, va, rs, ra = struct.unpack_from("<IIII", pe, off + 8)
        out.append((nm, va, vs, ra, rs))
        off += 40
    return out


def pe_read_va(pe, va, n):
    for nm, v, vs, ra, rs in pe_sections(pe):
        if v <= va < v + vs and va - v < rs:
            o = ra + (va - v)
            return pe[o:o + n]
    raise ValueError(f"VA {va:#x} not mapped")


def load_family_lists(pe):
    legacy = struct.unpack_from("<8H", pe_read_va(pe, LEGACY_LIST_VA, 16))
    ec = struct.unpack_from("<6H", pe_read_va(pe, EC_LIST_VA, 12))
    return legacy, ec


def load_alphabets(pe):
    """dispatch-table alphabet pointers (index 0 = EC-path, 1 = E7A8)."""
    a0 = struct.unpack_from("<Q", pe_read_va(pe, VA_ALPHA_TABLE, 8))[0]
    a1 = struct.unpack_from("<Q", pe_read_va(pe, VA_ALPHA_TABLE + 24, 8))[0]
    return (pe_read_va(pe, a0, 72).decode("latin1"),
            pe_read_va(pe, a1, 72).decode("latin1"))


# ---------------------------------------------------------------------------
# response -> master map  (SMM fn 0x8E18 — emulation-verified §11.3)
# ---------------------------------------------------------------------------
def response_to_master(resp32: bytes, family: int, alphabet: str) -> str:
    if len(resp32) < 32:
        raise ValueError("need the full 32-byte EC response")
    if family == 0x8FC8:
        return "".join(alphabet[(resp32[i] + resp32[i + 16]) % 72]
                       for i in range(16))
    # CF1B / 3FE2 / 1B58 / 9ABE: raw-copy branch — verbatim
    return resp32[:16].decode("latin1")


def response_to_code2(resp32: bytes, family: int, alphabet: str) -> str:
    """the second half (challenge 'code 2' candidate)."""
    if family == 0x8FC8:
        return "".join(alphabet[(resp32[i + 16] + resp32[i]) % 72]
                       for i in range(16))
    return resp32[16:32].decode("latin1")


# ---------------------------------------------------------------------------
# oracle 1: the machine's own EC (bare metal, root) — /dev/port mailbox I/O
# ---------------------------------------------------------------------------
PORT_IDX, PORT_DAT, WIN_BASE, SEL_CMD = 0x910, 0x911, 0x10, 0x00
TIMEOUT_S = 2.0


class PortIO:
    def __init__(self):
        self.f = open("/dev/port", "r+b", buffering=0)

    def out(self, port, val):
        self.f.seek(port)
        self.f.write(bytes([val]))

    def inp(self, port):
        self.f.seek(port)
        return self.f.read(1)[0]


class ECSession:
    """cmd-0x17 packet transport over the 0x910/0x911 mailbox (§11.4)."""

    def __init__(self, io=None):
        self.io = io or PortIO()

    def win_write(self, i, v):
        self.io.out(PORT_IDX, WIN_BASE + i)
        self.io.out(PORT_DAT, v)

    def win_read(self, i):
        self.io.out(PORT_IDX, WIN_BASE + i)
        return self.io.inp(PORT_DAT)

    def wait_ack(self):
        end = time.monotonic() + TIMEOUT_S
        while time.monotonic() < end:
            self.io.out(PORT_IDX, SEL_CMD)
            if self.io.inp(PORT_DAT) == 0:
                return True
        return False

    def doorbell(self, cmd):
        self.io.out(PORT_IDX, SEL_CMD)
        self.io.out(PORT_DAT, cmd)
        return self.wait_ack()

    def xfer_write(self, data):
        self.win_write(3, 0)
        self.win_write(2, 0)
        if not self.doorbell(0x17):
            return False
        off = 0
        while off < len(data):
            n = min(8, len(data) - off)
            for i in range(n):
                self.win_write(4 + i, data[off + i])
            self.win_write(3, n)
            self.win_write(2, 1)
            if not self.wait_ack():
                return False
            end = time.monotonic() + TIMEOUT_S
            while time.monotonic() < end:
                if (self.win_read(2) & 1) == 0:
                    break
            else:
                return False
            off += n
        self.win_write(3, 0)
        self.win_write(2, 1)               # end-of-transfer
        return self.wait_ack()

    def xfer_read(self, length):
        out = bytearray()
        self.win_write(3, 0)
        self.win_write(2, 0)
        if not self.doorbell(0x17):
            return bytes(out)
        while len(out) < length:
            cnt = 0
            end = time.monotonic() + TIMEOUT_S
            while time.monotonic() < end:
                if self.win_read(2) & 1:
                    cnt = self.win_read(3)
                    break
            if not cnt:
                break
            cnt = min(cnt, 8, length - len(out))
            for i in range(cnt):
                out.append(self.win_read(4 + i))
            self.win_write(3, 0)           # consumed
            self.win_write(2, 0)
        return bytes(out)

    def generate(self, tag: bytes, family: int):
        """the §11 type-6 GENERATE session; returns (resp32, status)."""
        self.win_write(2, 3)               # sub  = 3
        self.win_write(3, 6)               # type = 6  (GENERATE)
        if not self.doorbell(0x21):
            raise RuntimeError("EC did not acknowledge session 0x21")
        if not self.xfer_write(tag):
            raise RuntimeError("tag transfer failed")
        if not self.xfer_write(bytes([FAMILY_LSB[family]])):
            raise RuntimeError("family transfer failed")
        resp = self.xfer_read(32)
        if len(resp) < 32:
            raise RuntimeError(f"short response ({len(resp)} bytes) — "
                               "EC gated the session")
        st = self.xfer_read(1)
        status = st[0] if st else None
        if status != 0:
            raise RuntimeError(f"EC status byte {status:#04x} "
                               f"(0 = success; see fn 0x31B4 map)")
        return resp, status


# ---------------------------------------------------------------------------
# oracle 0: local families — emulate the machine's own generator (fn_b)
# ---------------------------------------------------------------------------
def generate_local(pe_path: str, tag: str, suffix_word: int):
    from dell_v2_keygen import locate_fn_b, generate  # noqa
    pe = open(pe_path, "rb").read()
    emu, fn_b = locate_fn_b(pe)          # (emulator, generator entry VA)
    rv, out = generate(emu, fn_b, tag, suffix_word)
    if rv != 0:
        raise RuntimeError(f"module generator returned {rv:#x} "
                           f"(family not supported locally)")
    return out.decode("latin1")


# ---------------------------------------------------------------------------
def selftest(pe_path):
    ok = True
    pe = open(pe_path, "rb").read()
    alpha_ec, _ = load_alphabets(pe)

    # 1) response->code maps vs the emulation vectors of §11.3
    canned = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ012345"
    checks = [
        ("CF1B verbatim", response_to_master(canned, 0xCF1B, alpha_ec),
         "ABCDEFGHIJKLMNOP"),
        ("8FC8 alphabet", response_to_master(canned, 0x8FC8, alpha_ec),
         "2rk9L1Gq53kZkFx["),
    ]
    for name, got, exp in checks:
        good = got == exp
        ok &= good
        print(f"  {'PASS' if good else 'FAIL'}  {name}: {got!r}"
              f"{'' if good else f' (expected {exp!r})'}")

    # 2) local-family path: E7A8 on the 3090's own module
    got = generate_local(pe_path, DEFAULT_TAG, 0xE7A8)
    good = got == "fUf4Ju6GcBdf0nY1"   # module-emulation output (§11, action log)
    ok &= good
    print(f"  {'PASS' if good else 'FAIL'}  E7A8 via module emulation: {got!r}")

    # 3) family lists sane
    legacy, ec = load_family_lists(pe)
    good = (0xCF1B in ec and 0x8FC8 in ec and 0xE7A8 in legacy)
    ok &= good
    print(f"  {'PASS' if good else 'FAIL'}  family lists: "
          f"legacy={[hex(x) for x in legacy[:7]]} ec={[hex(x) for x in ec[:5]]}")
    print("SELF-TEST:", "PASS" if ok else "FAIL")
    return ok


def main():
    ap = argparse.ArgumentParser(
        description="tag + suffix -> Dell BIOS master password "
                    "(family-own implementations; see module docstring)")
    ap.add_argument("--tag", default=DEFAULT_TAG)
    ap.add_argument("--suffix", default="CF1B",
                    help="4-hex suffix, e.g. CF1B, 8FC8, E7A8, 9ABE")
    ap.add_argument("--pe", default=DEFAULT_PE,
                    help="vault-module PE of the target BIOS "
                         "(default: the committed 3090 2.27.0 module)")
    ap.add_argument("--oracle", default="local",
                    help="local | resp:HEX(64 hex chars, the 32B EC response)")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(0 if selftest(args.pe) else 1)

    tag = args.tag.upper()
    try:
        suffix_word = int(args.suffix, 16)
    except ValueError:
        sys.exit(f"suffix must be 4 hex digits, e.g. CF1B")
    print(f"Dell master keygen — tag {tag}, suffix {args.suffix.upper()} "
          f"({suffix_word:#06x})")
    print(f"module: {os.path.basename(args.pe)}\n")

    if not os.path.exists(args.pe):
        sys.exit(f"vault module PE not found: {args.pe}")

    pe = open(args.pe, "rb").read()
    alpha_ec, _ = load_alphabets(pe)

    # ---- local families: module emulation, fully offline -------------------
    if suffix_word in LOCAL_FAMILIES:
        try:
            code = generate_local(args.pe, tag, suffix_word)
        except RuntimeError as e:
            legacy_note = {
                0xBF97: "(the 2.27.0 module dropped legacy local generation — "
                         "§10; for a pre-EC-era machine use dell_keygen.py)",
            }.get(suffix_word, "")
            sys.exit(f"module generator refused suffix {args.suffix}: {e}\n"
                     f"{legacy_note}")
        print(f"MASTER PASSWORD : {code}")
        print("(generated by emulating this machine's own vault module)")
        return 0

    # ---- EC families: §11 session + response->code map ---------------------
    if suffix_word not in EC_FAMILIES:
        sys.exit(f"unknown suffix {args.suffix}; known: "
                 + ", ".join(f"{f:04X}" for f in (*LOCAL_FAMILIES, *sorted(EC_FAMILIES))))

    if args.oracle.startswith("resp:"):
        try:
            resp = bytes.fromhex(args.oracle[5:])
        except ValueError:
            sys.exit("resp: must be 64 hex chars")
        if len(resp) < 32:
            sys.exit("resp: need 32 bytes (64 hex chars)")
    else:
        # oracle local: needs bare-metal root
        if os.geteuid() != 0:
            sys.exit("EC families need the machine's EC as oracle — run as "
                     "root on the target machine (sudo), or use "
                     "--oracle resp:HEX offline with a captured response.")
        print("opening EC mailbox (ports 0x910/0x911) ...")
        try:
            sess = ECSession()
            resp, status = sess.generate(tag.encode(), suffix_word)
        except (OSError, RuntimeError) as e:
            print(f"\nEC session failed: {e}")
            print("tips: bare metal (not VM); if the EC gates by state, "
                  "re-run with the BIOS challenge screen up (reboot to the "
                  "prompt, warm-reset into Linux without removing power).")
            return 1
        print(f"EC response (32B): {resp.hex()}")
        print(f"EC status        : {status:#04x}\n")

    master = response_to_master(resp, suffix_word, alpha_ec)
    code2 = response_to_code2(resp, suffix_word, alpha_ec)
    print(f"MASTER PASSWORD : {master}")
    print(f"second candidate: {code2}   (challenge 'code 2' half)")
    print("\nEnter the MASTER PASSWORD at the BIOS password prompt, then "
          "Ctrl+Enter+Enter.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
